### ISSUE TITLE
file tv_grab_wg notre executable

### ISSUE THREAD

**Issue by Sellig28** [linuxserver/docker-tvheadend-armhf#6]
Hi,
tv_grab_wg and tv_grab_file are notre executable, so they aren't seen on tvheadend.
Just add chmod a+x to tv_grab_files.
Beware in tv_grab_wg the xml file ils waiting in /config/data

Big thanks for this great work, i use it on my rpi3 with libreelec.

**Comment by tobbenb** [comment]
I'll fix this when I have some time later today

**Comment by Sellig28** [comment]
Thank you, I will tell you if it's okay.
Thank you again.

**Comment by tobbenb** [comment]
This issue was fixed by #10 and #9
